
import java.util.Vector;
import static javafx.beans.binding.Bindings.select;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Frame1 extends javax.swing.JFrame {
    //ราคาไส้
    String price [] = {"5","5","5","5","5","5","5","5","5"};
    DefaultTableModel model;
    //หาราคารวม
    double total = 0.0;
    //เก็บตำแหน่งที่ผู้ใช้เลือก
    int selected;
    
    
    public Frame1() {
        initComponents();
        t1.setText(price[0]);
        model=(DefaultTableModel)tb.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bn3 = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        cbFood = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        bn1 = new javax.swing.JButton();
        bn2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        lbtotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel3.setBackground(new java.awt.Color(51, 255, 204));
        jLabel3.setText("jLabel3");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iron-man-2550x1440-fan-art-minimal-hd-9769.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ร้านโตเกียว");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ร้านโตเกียว A&G");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 36, -1, -1));

        bn3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bn3.setText("เสร็จสิ้น");
        bn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bn3MouseClicked(evt);
            }
        });
        bn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn3ActionPerformed(evt);
            }
        });
        getContentPane().add(bn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 342, 150, 65));

        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("รายการเมนู");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 98, -1, -1));

        cbFood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ไส้คัสตาร์ด", "ไส้ฮอตด็อก", "ไส้สังขยา", "ไส้พริกเผาหมูหยอง", "ไส้หมูสับ", "ไส้ครีมวานิลา" }));
        cbFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFoodActionPerformed(evt);
            }
        });
        getContentPane().add(cbFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 95, 153, -1));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("ราคา/ชิ้น");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 98, -1, -1));

        t1.setEnabled(false);
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 95, 53, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("จำนวน");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 98, -1, -1));

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 95, 57, -1));

        bn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bn1.setText("เพิ่ม");
        bn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn1ActionPerformed(evt);
            }
        });
        getContentPane().add(bn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 135, 150, 65));

        bn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bn2.setText("ลบ");
        bn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bn2MouseClicked(evt);
            }
        });
        bn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn2ActionPerformed(evt);
            }
        });
        getContentPane().add(bn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 233, 150, 65));

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "รายการเมนู", "ราคา/ชิ้น", "จำนวน", "ราคา"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tb);
        if (tb.getColumnModel().getColumnCount() > 0) {
            tb.getColumnModel().getColumn(0).setResizable(false);
            tb.getColumnModel().getColumn(1).setResizable(false);
            tb.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 135, -1, 272));

        lbtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbtotal.setForeground(new java.awt.Color(255, 255, 255));
        lbtotal.setText("ราคารวมทั้งหมด");
        getContentPane().add(lbtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 425, 452, 61));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iron-man-2550x1440-fan-art-minimal-hd-9769.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 490));

        setBounds(0, 0, 718, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void bn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn3ActionPerformed
                      // TODO add your handling code here:
    }//GEN-LAST:event_bn3ActionPerformed

    private void cbFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFoodActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void bn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn1ActionPerformed
        Vector v=new Vector();
        if (t2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,"กรุณาใส่จำนวน","คำเตือน",
                JOptionPane.ERROR_MESSAGE);
           
        }
        v.add(cbFood.getSelectedItem().toString());
        v.add(t1.getText());
        v.add(t2.getText());
        double money = Double.valueOf(t1.getText())*Double.valueOf(t2.getText());
        v.add(money);
        total+=money;
        model.addRow(v);
        lbtotal.setText("ราคารวมทั้งหมด : "+total+" บาท");
        // TODO add your handling code here:
    }//GEN-LAST:event_bn1ActionPerformed

    private void bn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn2ActionPerformed
        int Selected = 0;
        int select = 0;
        double moneySelected;// TODO add your handling code here:
        moneySelected = Double.valueOf(tb.getValueAt(select,3).toString());
        System.out.println("แสดงจำนวนเงินที่ลบออก = "+moneySelected);
        total-=moneySelected;
        lbtotal.setText("ราคาทั้งหมด : "+total+" บาท");
        if(0.00 == total){
            lbtotal.setText("ราคารวมทั้งหมด : 0.00บาท");
        } 
        model.removeRow(Selected);
        
    }//GEN-LAST:event_bn2ActionPerformed

    private void bn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bn2MouseClicked
        selected = tb.getSelectedRow();
        System.out.println("แถวที่เลือก = "+selected);// TODO add your handling code here:
        
    }//GEN-LAST:event_bn2MouseClicked

    private void bn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bn3MouseClicked
        JOptionPane.showMessageDialog(this,"ขอบคุณที่ใช่บริการครับ","คำเตือน",
                JOptionPane.ERROR_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_bn3MouseClicked
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Frame1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bn1;
    private javax.swing.JButton bn2;
    private javax.swing.JButton bn3;
    private javax.swing.JComboBox<String> cbFood;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel lbtotal;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTable tb;
    // End of variables declaration//GEN-END:variables
}
